version: "3.9"
networks:
 deploy-guide-dev-net: #{}
  driver: bridge
  # external: true

services:
 app:
  container_name: deploy-guide
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "80:8080"
  # network_mode: bridge
  networks:
   - deploy-guide-dev-net
  depends_on:
   - postgres

 postgres:
  hostname: postgres
  container_name: postgres 
  image: postgres:latest
  environment:
   - POSTGRES_DB=VodorotTestTaskDB
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=1
  volumes:
   - postgres-data:/var/lib/postgresql/data
  ports:
   - "5430:5432"
  restart: always
  networks: 
   - deploy-guide-dev-net
  # network_mode: bridge

volumes:
 postgres-data: